server:
   port: 8040
spring:
  application:
    name: gateway-server
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        serviceId: config-server
#      profile: rabbitmq
#      label: test
  http:
    multipart:
      max-file-size: 300Mb
      max-request-size: 300Mb
    encoding:
      charset: UTF-8
      force: true
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.242:38761/eureka/
  instance:
    statusPageUrlPath: /swagger-ui.html
    lease-expiration-duration-in-seconds: 30 
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    metadata-map:
      weight: 11
management:
  security:
    enabled: false
zuul:
  routes:
    scp-apianalysiscomponent:
      path: /VIID/**
      strip-prefix: false
  host:  
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  
hystrix:  
  command:  
    default:  
      execution:  
        isolation:  
          thread:  
            timeoutInMilliseconds: 60000
ribbon:  
  ReadTimeout: 60000  
  ConnectTimeout: 60000
